blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/sfo2001/platform-linux_arm/wiki
    about: Check the wiki before opening an issue
  - name: Discussions
    url: https://github.com/sfo2001/platform-linux_arm/discussions
    about: Questions and general discussion
