; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:raspberrypi_3b]
platform = linux_arm
framework = lgpio
board = raspberrypi_3b

[env:raspberrypi_400]
platform = linux_arm
framework = lgpio
board = raspberrypi_400

[env:raspberrypi_cm4]
platform = linux_arm
framework = lgpio
board = raspberrypi_cm4

[env:raspberrypi_zero2w]
platform = linux_arm
framework = lgpio
board = raspberrypi_zero2w

[env:raspberrypi_5_64bit]
platform = linux_arm
board = raspberrypi_5
framework = lgpio
board_build.arch = aarch64
