; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:raspberrypi_3b]
platform = linux_arm
framework = pigpio
board = raspberrypi_3b

[env:raspberrypi_400]
platform = linux_arm
framework = pigpio
board = raspberrypi_400

[env:raspberrypi_cm4]
platform = linux_arm
framework = pigpio
board = raspberrypi_cm4

[env:raspberrypi_zero2w]
platform = linux_arm
framework = pigpio
board = raspberrypi_zero2w
